//TWITCH
export const LOG_IN_TWITCH = "LOG_IN_TWITCH";
export const GET_MESSAGE_TWITCH = "GET_MESSAGE_TWITCH";
export const GET_MESSAGE_WHEEL_TWITCH = "GET_MESSAGE_WHEEL_TWITCH";
export const CLEAR_MESSAGES_WHEEL = "CLEAR_MESSAGES_WHEEL";
export const SET_ONLY_SUBS = "SET_ONLY_SUBS";
export const REMOVE_MESSAGES_WHEEL = "REMOVE_MESSAGES_WHEEL";

//OBS
export const LOG_IN_OBS = "LOG_IN_OBS";
export const GET_SCENES_OBS = "GET_SCENES_OBS";
export const GET_SCENE_OBS = "GET_SCENE_OBS";

//GLOBAL
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_STATE = "CLEAR_STATE";
